### ISSUE TITLE
Integration tests fail to change browser size, opera

### ISSUE THREAD

**Issue by nathanaeljones** [imazen/slimmage#45]
8 tests failed.
changing to 800
	should be the right size (800): [setWindowSize(800,600)] Error response status: 13, UnknownError - An unknown server-side error occurred while processing the command. Selenium error: Not supported in OperaDriver yet Error: [setWindowSize(800,600)] Error response status: 13, UnknownError - An unknown server-side error occurred while processing the command. Selenium error: Not supported in OperaDriver yet
    at exports.newError (/home/travis/build/imazen/slimmage/node_modules/wd/lib/utils.js:139:13)
    at /home/travis/build/imazen/slimmage/node_modules/wd/lib/callbacks.js:33:23
    at /home/travis/build/imazen/slimmage/node_modules/wd/lib/webdriver.js:174:5
    at Request._callback (/home/travis/build/imazen/slimmage/node_modules/wd/lib/http-utils.js:85:7)
    at Request.self.callback (/home/travis/build/imazen/slimmage/node_modules/wd/node_modules/request/request.js:364:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/home/travis/build/imazen/slimmage/node_modules/wd/node_modules/request/request.js:1318:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/home/travis/build/imazen/slimmage/node_modules/wd/node_modules/request/request.js:1266:12)
    at IncomingMessage.emit (events.js:117:20)
	should wait until the body has resized: [setWindowSize(800,600)] Error response status: 13, UnknownError - An unknown server-side error occurred while processing the command. Selenium error: Not supported in OperaDriver yet Error: [setWindowSize(800,600)] Error response status: 13, UnknownError - An unknown server-side error occurred while processing the command. Selenium error: Not supported in OperaDriver yet
    at exports.newError (/home/travis/build/imazen/slimmage/node_modules/wd/lib/utils.js:139:13)
    at /home/travis/build/imazen/slimmage/node_modules/wd/lib/callbacks.js:33:23
    at /home/travis/build/imazen/slimmage/node_modules/wd/lib/webdriver.js:174:5
    at Request._callback (/home/travis/build/imazen/slimmage/node_modules/wd/lib/http-utils.js:85:7)
    at Request.self.callback (/home/travis/build/imazen/slimmage/node_modules/wd/node_modules/request/request.js:364:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/home/travis/build/imazen/slimmage/node_modules/wd/node_modules/request/request.js:1318:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/home/travis/build/imazen/slimmage/node_modules/wd/node_modules/request/request.js:1266:12)
    at IncomingMessage.emit (events.js:117:20)
	should be the right size (800): [setWindowSize(800,600)] Error response status: 13, UnknownError - An unknown server-side error occurred while processing the command. Selenium error: Not supported in OperaDriver yet Error: [setWindowSize(800,600)] Error response status: 13, UnknownError - An unknown server-side error occurred while processing the command. Selenium error: Not supported in OperaDriver yet
    at exports.newError (/home/travis/build/imazen/slimmage/node_modules/wd/lib/utils.js:139:13)
    at /home/travis/build/imazen/slimmage/node_modules/wd/lib/callbacks.js:33:23
    at /home/travis/build/imazen/slimmage/node_modules/wd/lib/webdriver.js:174:5
    at Request._callback (/home/travis/build/imazen/slimmage/node_modules/wd/lib/http-utils.js:85:7)
    at Request.self.callback (/home/travis/build/imazen/slimmage/node_modules/wd/node_modules/request/request.js:364:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/home/travis/build/imazen/slimmage/node_modules/wd/node_modules/request/request.js:1318:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/home/travis/build/imazen/slimmage/node_modules/wd/node_modules/request/request.js:1266:12)
    at IncomingMessage.emit (events.js:117:20)
	should wait until the body has resized: [setWindowSize(800,600)] Error response status: 13, UnknownError - An unknown server-side error occurred while processing the command. Selenium error: Not supported in OperaDriver yet Error: [setWindowSize(800,600)] Error response status: 13, UnknownError - An unknown server-side error occurred while processing the command. Selenium error: Not supported in OperaDriver yet
    at exports.newError (/home/travis/build/imazen/slimmage/node_modules/wd/lib/utils.js:139:13)
    at /home/travis/build/imazen/slimmage/node_modules/wd/lib/callbacks.js:33:23
    at /home/travis/build/imazen/slimmage/node_modules/wd/lib/webdriver.js:174:5
    at Request._callback (/home/travis/build/imazen/slimmage/node_modules/wd/lib/http-utils.js:85:7)
    at Request.self.callback (/home/travis/build/imazen/slimmage/node_modules/wd/node_modules/request/request.js:364:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/home/travis/build/imazen/slimmage/node_modules/wd/node_modules/request/request.js:1318:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/home/travis/build/imazen/slimmage/node_modules/wd/node_modules/request/request.js:1266:12)
    at IncomingMessage.emit (events.js:117:20)
changing to 1024
	should be the right size (1024): [setWindowSize(1024,768)] Error response status: 13, UnknownError - An unknown server-side error occurred while processing the command. Selenium error: Not supported in OperaDriver yet Error: [setWindowSize(1024,768)] Error response status: 13, UnknownError - An unknown server-side error occurred while processing the command. Selenium error: Not supported in OperaDriver yet
    at exports.newError (/home/travis/build/imazen/slimmage/node_modules/wd/lib/utils.js:139:13)
    at /home/travis/build/imazen/slimmage/node_modules/wd/lib/callbacks.js:33:23
    at /home/travis/build/imazen/slimmage/node_modules/wd/lib/webdriver.js:174:5
    at Request._callback (/home/travis/build/imazen/slimmage/node_modules/wd/lib/http-utils.js:85:7)
    at Request.self.callback (/home/travis/build/imazen/slimmage/node_modules/wd/node_modules/request/request.js:364:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/home/travis/build/imazen/slimmage/node_modules/wd/node_modules/request/request.js:1318:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/home/travis/build/imazen/slimmage/node_modules/wd/node_modules/request/request.js:1266:12)
    at IncomingMessage.emit (events.js:117:20)
	should wait until the body has resized: [setWindowSize(1024,768)] Error response status: 13, UnknownError - An unknown server-side error occurred while processing the command. Selenium error: Not supported in OperaDriver yet Error: [setWindowSize(1024,768)] Error response status: 13, UnknownError - An unknown server-side error occurred while processing the command. Selenium error: Not supported in OperaDriver yet
    at exports.newError (/home/travis/build/imazen/slimmage/node_modules/wd/lib/utils.js:139:13)
    at /home/travis/build/imazen/slimmage/node_modules/wd/lib/callbacks.js:33:23
    at /home/travis/build/imazen/slimmage/node_modules/wd/lib/webdriver.js:174:5
    at Request._callback (/home/travis/build/imazen/slimmage/node_modules/wd/lib/http-utils.js:85:7)
    at Request.self.callback (/home/travis/build/imazen/slimmage/node_modules/wd/node_modules/request/request.js:364:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/home/travis/build/imazen/slimmage/node_modules/wd/node_modules/request/request.js:1318:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/home/travis/build/imazen/slimmage/node_modules/wd/node_modules/request/request.js:1266:12)
    at IncomingMessage.emit (events.js:117:20)
	should be the right size (1024): [setWindowSize(1024,768)] Error response status: 13, UnknownError - An unknown server-side error occurred while processing the command. Selenium error: Not supported in OperaDriver yet Error: [setWindowSize(1024,768)] Error response status: 13, UnknownError - An unknown server-side error occurred while processing the command. Selenium error: Not supported in OperaDriver yet
    at exports.newError (/home/travis/build/imazen/slimmage/node_modules/wd/lib/utils.js:139:13)
    at /home/travis/build/imazen/slimmage/node_modules/wd/lib/callbacks.js:33:23
    at /home/travis/build/imazen/slimmage/node_modules/wd/lib/webdriver.js:174:5
    at Request._callback (/home/travis/build/imazen/slimmage/node_modules/wd/lib/http-utils.js:85:7)
    at Request.self.callback (/home/travis/build/imazen/slimmage/node_modules/wd/node_modules/request/request.js:364:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/home/travis/build/imazen/slimmage/node_modules/wd/node_modules/request/request.js:1318:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/home/travis/build/imazen/slimmage/node_modules/wd/node_modules/request/request.js:1266:12)
    at IncomingMessage.emit (events.js:117:20)
	should wait until the body has resized: [setWindowSize(1024,768)] Error response status: 13, UnknownError - An unknown server-side error occurred while processing the command. Selenium error: Not supported in OperaDriver yet Error: [setWindowSize(1024,768)] Error response status: 13, UnknownError - An unknown server-side error occurred while processing the command. Selenium error: Not supported in OperaDriver yet
    at exports.newError (/home/travis/build/imazen/slimmage/node_modules/wd/lib/utils.js:139:13)
    at /home/travis/build/imazen/slimmage/node_modules/wd/lib/callbacks.js:33:23
    at /home/travis/build/imazen/slimmage/node_modules/wd/lib/webdriver.js:174:5
    at Request._callback (/home/travis/build/imazen/slimmage/node_modules/wd/lib/http-utils.js:85:7)
    at Request.self.callback (/home/travis/build/imazen/slimmage/node_modules/wd/node_modules/request/request.js:364:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/home/travis/build/imazen/slimmage/node_modules/wd/node_modules/request/request.js:1318:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/home/travis/build/imazen/slimmage/node_modules/wd/node_modules/request/request.js:1266:12)
    at IncomingMessage.emit (events.js:117:20)

**Comment by nathanaeljones** [comment]
Not supported by opera. fixed.
